-- Sync the production Festival of Stars schema used by the React announcement site.
-- Apply this migration to the FLC Supabase project before deployment.

create table if not exists public.festival_announcements (
  event_id uuid primary key references public.events(id) on delete cascade,
  slug text not null unique,
  published_at timestamptz,
  registration_enabled boolean not null default true,
  hero_image_url text,
  seo_title text,
  seo_description text,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.festival_talent_categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  tagline text not null,
  description text not null,
  accent text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.festival_registrations (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  full_name text not null,
  email text not null,
  mobile text,
  guests smallint not null default 0 check (guests between 0 and 10),
  attending_service text,
  message text,
  created_at timestamptz not null default now(),
  constraint festival_registrations_name_ck check (char_length(trim(full_name)) between 2 and 120),
  constraint festival_registrations_email_ck check (char_length(trim(email)) between 5 and 254)
);

create unique index if not exists festival_registrations_event_email_uq
  on public.festival_registrations(event_id, lower(trim(email)));

create table if not exists public.festival_talent_submissions (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  talent_category_id uuid not null references public.festival_talent_categories(id),
  full_name text not null,
  email text not null,
  mobile text,
  performance_title text not null,
  description text not null,
  sample_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  constraint festival_talent_name_ck check (char_length(trim(full_name)) between 2 and 120),
  constraint festival_talent_title_ck check (char_length(trim(performance_title)) between 2 and 160),
  constraint festival_talent_description_ck check (char_length(trim(description)) between 10 and 2000)
);

create table if not exists public.festival_analytics_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  event_type text not null,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint festival_analytics_event_type_ck check (
    event_type in (
      'page_view','register_click','register_submit','talent_view',
      'talent_select','talent_submit','share_click','directions_click','sound_toggle'
    )
  )
);

create index if not exists festival_analytics_event_time_idx
  on public.festival_analytics_events(event_id, created_at desc);

insert into public.festival_talent_categories (slug,name,tagline,description,accent,sort_order)
values
  ('singing','SINGING','Raise your voice.','Perform a song, lead worship, or bring a sound that gets the room singing.','#19ddd1',1),
  ('rap','RAP','Bring your bars.','Tell your story through rhythm, flow, poetry, and a message that makes people think.','#ffc526',2),
  ('acting','ACTING','Own the stage.','Bring a monologue, skit, spoken word, scene, or creative performance to life.','#ff6148',3)
on conflict (slug) do update set
  name=excluded.name,tagline=excluded.tagline,description=excluded.description,
  accent=excluded.accent,sort_order=excluded.sort_order,is_active=true;

insert into public.festival_announcements (
  event_id,slug,published_at,registration_enabled,hero_image_url,seo_title,seo_description,content
)
select
  e.id,
  'festival-of-stars',
  coalesce(
    (select published_at from public.festival_announcements fa where fa.event_id=e.id),
    now()
  ),
  true,
  '/festival-assets/festival-moodboard.jpg',
  'Festival of Stars · First Love Church Philippines',
  'Shine, belong, and make a difference at Festival of Stars. Worship, community, messages, and creative performances for youth and young adults.',
  jsonb_build_object(
    'kicker','ONE CHURCH · MANY STORIES · ONE BIG CELEBRATION',
    'tagline','SHINE · BELONG · MAKE A DIFFERENCE',
    'hero_copy','A high-energy celebration for youth and young adults — packed with worship, real community, creative expression, and purpose.',
    'audience','FOR YOUTH & YOUNG ADULTS',
    'age_label','AGES 13 AND UP',
    'banner_title','Every star has a story.',
    'banner_copy','Come ready to shine.',
    'about_title','Why Festival of Stars?',
    'about_copy','Festival of Stars is more than an event. It is a space where young people can worship boldly, meet people, discover purpose, and use their creativity for something bigger.',
    'about_body','Expect a night built around faith, friendship, music, stories, stage performances, games, and moments that make you want to come back with your whole squad.',
    'talent_title','Bring your talent to the stars.',
    'talent_intro','Your gift belongs on a stage. Pick a lane, prepare your piece, and let your creativity point people toward something bigger.',
    'visit_title','Same mission. Brighter tomorrow.',
    'visit_items',jsonb_build_array(
      jsonb_build_object('title','Bring your people','copy','Invite a friend, classmate, teammate, sibling, or anyone who needs a night to belong.'),
      jsonb_build_object('title','Bring your creativity','copy','Come ready to sing, rap, act, create, dance, cheer, and celebrate the gifts God gave you.'),
      jsonb_build_object('title','Bring your story','copy','You do not have to have it all figured out. Show up, meet people, and take your next step.')
    ),
    'faqs',jsonb_build_array(
      jsonb_build_object('question','Who can attend?','answer','Festival of Stars is designed for youth and young adults ages 13 and up.'),
      jsonb_build_object('question','Can I bring a friend?','answer','Yes. Invite friends, classmates, teammates, and family members.'),
      jsonb_build_object('question','Can I perform?','answer','Yes. Singing, rap, and acting submissions are open through the Creative Showcase registration.'),
      jsonb_build_object('question','What should I bring?','answer','Bring yourself, your friends, and your energy. Bring any approved performance materials if you are participating in the showcase.')
    )
  )
from public.events e
where lower(regexp_replace(trim(e.name),'[^a-zA-Z0-9]+','-','g'))='festival-of-stars'
on conflict (event_id) do update set
  slug=excluded.slug,registration_enabled=excluded.registration_enabled,
  hero_image_url=excluded.hero_image_url,seo_title=excluded.seo_title,
  seo_description=excluded.seo_description,content=excluded.content,updated_at=now();

alter table public.festival_announcements enable row level security;
alter table public.festival_talent_categories enable row level security;
alter table public.festival_registrations enable row level security;
alter table public.festival_talent_submissions enable row level security;
alter table public.festival_analytics_events enable row level security;

drop policy if exists festival_announcements_public_select on public.festival_announcements;
create policy festival_announcements_public_select on public.festival_announcements
for select to anon,authenticated using (published_at is not null and published_at <= now());

drop policy if exists festival_talent_public_select on public.festival_talent_categories;
create policy festival_talent_public_select on public.festival_talent_categories
for select to anon,authenticated using (is_active=true);

drop policy if exists festival_registration_public_insert on public.festival_registrations;
create policy festival_registration_public_insert on public.festival_registrations
for insert to anon,authenticated with check (true);

drop policy if exists festival_talent_public_insert on public.festival_talent_submissions;
create policy festival_talent_public_insert on public.festival_talent_submissions
for insert to anon,authenticated with check (true);

drop policy if exists festival_analytics_public_insert on public.festival_analytics_events;
create policy festival_analytics_public_insert on public.festival_analytics_events
for insert to anon,authenticated with check (true);

revoke all on public.festival_announcements from anon,authenticated;
grant select on public.festival_announcements to anon,authenticated;
revoke all on public.festival_talent_categories from anon,authenticated;
grant select on public.festival_talent_categories to anon,authenticated;
revoke all on public.festival_registrations from anon,authenticated;
grant insert on public.festival_registrations to anon,authenticated;
revoke all on public.festival_talent_submissions from anon,authenticated;
grant insert on public.festival_talent_submissions to anon,authenticated;
revoke all on public.festival_analytics_events from anon,authenticated;
grant insert on public.festival_analytics_events to anon,authenticated;

create or replace function public.get_public_festival_of_stars(p_slug text default 'festival-of-stars')
returns jsonb
language sql
security definer
set search_path=public
stable
as $$
  select jsonb_build_object(
    'event',jsonb_build_object(
      'id',e.id,'name',e.name,'description',e.description,
      'start_at',e.start_at,'end_at',e.end_at,'location',e.location
    ),
    'announcement',jsonb_build_object(
      'slug',a.slug,'published_at',a.published_at,'registration_enabled',a.registration_enabled,
      'hero_image_url',a.hero_image_url,'seo_title',a.seo_title,
      'seo_description',a.seo_description,'content',a.content
    ),
    'talents',coalesce((
      select jsonb_agg(to_jsonb(tc)-'created_at' order by tc.sort_order)
      from public.festival_talent_categories tc where tc.is_active=true
    ),'[]'::jsonb)
  )
  from public.festival_announcements a
  join public.events e on e.id=a.event_id
  where a.slug=p_slug and a.published_at is not null and a.published_at <= now() and e.is_active=true
  limit 1;
$$;

revoke all on function public.get_public_festival_of_stars(text) from public;
grant execute on function public.get_public_festival_of_stars(text) to anon,authenticated;
notify pgrst,'reload schema';
